import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const publicPath = path.join(__dirname, "..", "public", "dog.webp")
const outPath = path.join(__dirname, "..", "lib", "dog-image.ts")
const data = fs.readFileSync(publicPath)
const base64 = data.toString("base64")
const content = `// Auto-generated by scripts/embed-dog.mjs - do not edit
export const DOG_IMAGE_DATA_URL = "data:image/webp;base64,${base64}" as const
`
fs.writeFileSync(outPath, content)
console.log("Generated lib/dog-image.ts")
